---

# This file is part of "Lecture at MPS Yokohama"
#
# "Lecture at MPS Yokohama"
# is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# "Lecture at MPS Yokohama"
# is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
# (c) Junya Kaneko <jyuneko@hotmail.com>

- name: install python3, pip3, and other necessary packages
  apt: name={{ item }} update_cache=yes
  become: yes
  become_method: sudo
  with_items:
    - python3
    - python3-pip
    - python3-pil
    - python3-numpy
    - python3-scipy
    - python3-matplotlib
    - python3-pandas
    - python3-nose
    - python3-six

- name: install virtualenv jupyter
  pip: name={{ item }} executable=pip3
  become: yes
  become_method: sudo
  with_items:
    - jupyter
    - virtualenv

- name: install tensorflow
  pip:
    name=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl
    virtualenv=/home/vagrant/venv virtualenv_site_packages=yes

- name: create jupyter config directory
  file: dest=/home/vagrant/.jupyter state=directory

- name: copy Jupyter config
  copy: src=jupyter_notebook_config.py dest=/home/vagrant/.jupyter/jupyter_notebook_config.py

- name: install Jupyter kernel having TensorFlow
  shell: /home/vagrant/venv/bin/python3 -m ipykernel install --user

- name: copy a script running Jupyter
  copy: src=run_jupyter.sh dest=/home/vagrant/run_jupyter.sh mode=u+rwx

- name: create project directories
  file: dest=/home/vagrant/{{ item }} state=directory
  with_items:
    - project
    - project/MNIST_data

- name: copy MNIST_data
  copy: src=MNIST_data/{{ item }} dest=/home/vagrant/project/MNIST_data/{{ item }}
  with_items:
    - t10k-images-idx3-ubyte.gz
    - t10k-labels-idx1-ubyte.gz
    - train-images-idx3-ubyte.gz
    - train-labels-idx1-ubyte.gz
